version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "garethbaumgart"
    commit-message:
      prefix: "NuGet"
      include: "scope"
    open-pull-requests-limit: 4
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
